### ISSUE TITLE
CEnum: Bitwise ORing support?

### ISSUE THREAD

**Issue by Gnimuc** [JuliaGPU/VulkanCore.jl#15]
Since bit masking is ubiquitously used in Vulkan, I think it would be nice to support bitwise `|`:
```julia
julia> vk.VK_DEBUG_REPORT_ERROR_BIT_EXT | vk.VK_DEBUG_REPORT_WARNING_BIT_EXT
ERROR: UndefVarError: enum_argument_error not defined
Stacktrace:
 [1] convert(::Type{VulkanCore.api.VkDebugReportFlagBitsEXT}, ::Int64) at C:\Users\Gnimuc\.julia\v0.
6\VulkanCore\src\CEnum.jl:91
 [2] |(::VulkanCore.api.VkDebugReportFlagBitsEXT, ::VulkanCore.api.VkDebugReportFlagBitsEXT) at C:\U
sers\Gnimuc\.julia\v0.6\VulkanCore\src\CEnum.jl:4
```
An esay workaround is simply to write `Cuint(vk.VK_DEBUG_REPORT_ERROR_BIT_EXT) | Cuint(vk.VK_DEBUG_REPORT_WARNING_BIT_EXT)`, but it seems `CEnum` do support bitwise `&`:
```julia
julia> vk.VK_DEBUG_REPORT_ERROR_BIT_EXT & vk.VK_DEBUG_REPORT_ERROR_BIT_EXT
VK_DEBUG_REPORT_ERROR_BIT_EXT(8)
```
<strike>Is this just a bug?</strike>

oh, I see:

https://github.com/JuliaGPU/VulkanCore.jl/blob/84a14c00e8efb6c2faaca707f35dd7afe2cb4a78/src/CEnum.jl#L91-L94

It seems this is intended, if so, I'm wondering what's the purpose of:

https://github.com/JuliaGPU/VulkanCore.jl/blob/84a14c00e8efb6c2faaca707f35dd7afe2cb4a78/src/CEnum.jl#L4

**Comment by SimonDanisch** [comment]
I guess what's happening is, that the result can't be converted to a valid enum, and `enum_argument_error` has been removed from Base .. ;)

**Comment by Gnimuc** [comment]
```C
typedef enum VkDebugReportFlagBitsEXT {
    VK_DEBUG_REPORT_INFORMATION_BIT_EXT = 0x00000001,
    VK_DEBUG_REPORT_WARNING_BIT_EXT = 0x00000002,
    VK_DEBUG_REPORT_PERFORMANCE_WARNING_BIT_EXT = 0x00000004,
    VK_DEBUG_REPORT_ERROR_BIT_EXT = 0x00000008,
    VK_DEBUG_REPORT_DEBUG_BIT_EXT = 0x00000010, 
} VkDebugReportFlagBitsEXT;
```
This is the definition of [`VkDebugReportFlagBitsEXT`](https://vulkan.lunarg.com/doc/view/1.0.37.0/linux/vkspec.chunked/ch32s02.html), the result of `vk.VK_DEBUG_REPORT_ERROR_BIT_EXT | vk.VK_DEBUG_REPORT_WARNING_BIT_EXT` is `0x0a` a.k.a "1010" which is indeed not a member of `VkDebugReportFlagBitsEXT`. However, The bit masking flag "1010" is actually used as an input parameter of `VkDebugReportCallbackCreateInfoEXT`, it should be of type `vk.VkDebugReportFlagsEXT`(UInt32), not `VkDebugReportFlagBitsEXT`, so I think the assumption of the following two functions are not appropriate:

https://github.com/JuliaGPU/VulkanCore.jl/blob/84a14c00e8efb6c2faaca707f35dd7afe2cb4a78/src/CEnum.jl#L4-L5

A quick fix would be:
```julia
Base.(:|)(a::T, b::T) where {T<:Cenum} = UInt32(a) | UInt32(b)
Base.(:&)(a::T, b::T) where {T<:Cenum} = UInt32(a) & UInt32(b)
```

cc SimonDanisch
