### ISSUE TITLE
Make CEnum an independent package?

### ISSUE THREAD

**Issue by Gnimuc** [JuliaGPU/VulkanCore.jl#18]
So other c wrappers can use it without adding VulkanCore as a dependency or copy-pasting the file CEnum.jl and the corresponding license.

**Comment by SimonDanisch** [comment]
hm, there were plans to integrate it with clang or julia base. For simplicity and moving on, we could also just move it to it's own package, if you like!

**Comment by Gnimuc** [comment]
> there were plans to integrate it with clang or julia base.

That would be great! Is there any issue tracker for this?

**Comment by Gnimuc** [comment]
Hi @SimonDanisch, according to a recent discussion on Slack, I feel like there is little possibility that the CEnum will be integrated into Julia base, so could you revisit this https://github.com/ihnorton/Clang.jl/pull/162  at your convenience? If you don't have time to do it, I'd like to cherry-pick the commits and submit a PR.

**Comment by SimonDanisch** [comment]
Please go ahead :) I likely won't have any time for this in the next days!

**Comment by Gnimuc** [comment]
I just registered the package under JuliaInterop: https://github.com/JuliaLang/METADATA.jl/pull/20639
