### ISSUE TITLE
Scope of this package?

### ISSUE THREAD

**Issue by Gnimuc** [JuliaGPU/VulkanCore.jl#25]
The package name somehow implies this package is only for Vulkan Core API. Should we also mantain KHR extensions or all published extensions in this package? Maybe it's a good idea to maintain everything in one place and rename the package to Vulkan.jl? Following the naming convention of the JuliaGL org, [Vulkan.jl](https://github.com/JuliaGPU/Vulkan.jl) can be renamed to VKAbstraction.jl accordingly.

**Comment by SimonDanisch** [comment]
The idea was, that almost nobody should be working with VulkanCore directly, so it was supposed to get the more awkward name... But the core only means "core of the Julia Vulkan libraries", so extensions are definitely in the scope ;)

**Comment by Gnimuc** [comment]
Ah, these two "core"s are not the same thing, thanks for the clarification, makes sense to me now.  Let's tag the new version.
