### ISSUE TITLE
Standardize the use of the C wrapper

### ISSUE THREAD

**Issue by serenity4** [JuliaGPU/VulkanCore.jl#33]
Would there be an interest in exposing a safe way to use the generated API? It requires previous experience with C wrappers to actually use the library with a minimum of crashes and do something meaningful with it. In the end, there are several ways to deal with this, but it requires a lot of time and efforts to first figure it out and then write the code (because the API is huge). Personally I struggled a lot with finding efficient ways of making sure pointers stay valid.

I've taken a programmatic approach with [this wrapper](https://github.com/serenity4/Vulkan.jl/blob/codegen-refactor/generated/vulkan_wrapper.jl), we may reuse the [generating code](https://github.com/serenity4/Vulkan.jl/tree/codegen-refactor/generator) and tweak it if necessary. Currently it generates the following:

1. Mutable structs around Vulkan handles (e.g. `VkInstance`, which is just a `Ptr{Cvoid}`) to allow finalizers to be registered.
2. Basic reference counting to ensure finalizers don't destroy a handle while it is the parent of a non-finalized object (since finalizer execution order is undefined).
3. New structs which guarantee that, if the corresponding API struct has pointer fields, these stay valid while the struct is alive (by putting strings/arrays/refs inside a dummy `Vector{Any}` and bundle it inside the struct).
4. Friendly ("julian") structs for those that are only returned and never requested by the API, with a conversion from their API counterparts. Basically, `VkBool32` is replaced by `Bool`, `NTuple{N, UInt8}` by `String`, `UInt32` by `VersionNumber` (if the field actually represents a version number).
5. Wrapper around API calls, including error checking. Some functions have implicit return values (which take the form of a pointer argument whose memory is mutated by the API), so the wrapper function generates a corresponding `Ref`, calls the API, dereference it. Other functions require being called twice: once for filling the length of an array to be filled by the API, and once with the initialized array of the right size. Certain functions/structs may have optional arguments but this is not captured inside VulkanCore. The generated functions/constructors expose keyword arguments when this is the case. Vulkan constructors (vkCreate...) are wrapped differently in that they automatically register a finalizer to the wrapped object with the parent handle (if applicable) and allocator used to create it (as required by the specification).

I'd like your opinion on whether these features would be interesting for VulkanCore, only a subset of it, or none. I don't really have an opinion myself, although I think that having a new VulkanWrapper.jl (or similar) package would only bring confusion when there already are VulkanCore.jl and Vulkan.jl. Another possibility is to choose to have Vulkan.jl be lower-level, just wrapping the Vulkan API with the above without introducing abstractions and leaving that to other packages. It could be a better approach actually, because high-level graphics libraries often tend to be huge and not composable. It also lines up more with what one might expect, that is a way to use Vulkan as a backend, not a user-level library.

**Comment by Gnimuc** [comment]
The scope of this package was clarified in https://github.com/JuliaGPU/VulkanCore.jl/issues/25, so all of these features should go into Vulkan.jl.

**Comment by serenity4** [comment]
Ok, thanks.

**Comment by Gnimuc** [comment]
> 1. Mutable structs around Vulkan handles (e.g. `VkInstance`, which is just a `Ptr{Cvoid}`) to allow finalizers to be registered.
> 2. Basic reference counting to ensure finalizers don't destroy a handle while it is the parent of a non-finalized object (since finalizer execution order is undefined).

Would this introduce overhead? VulkanHPP provides an option to let users decide whether to use the automatic resource management or not: https://github.com/KhronosGroup/Vulkan-Hpp#uniquehandle-for-automatic-resource-management

**Comment by Gnimuc** [comment]
I think VulkanHpp is a good reference to determine what kind of features should be provided by Vulkan.jl.

**Comment by serenity4** [comment]
> Would this introduce overhead? VulkanHPP provides an option to let users decide whether to use the automatic resource management or not: https://github.com/KhronosGroup/Vulkan-Hpp#uniquehandle-for-automatic-resource-management

I believe the overhead is negligible compared to the duration of the vkDestroy... functions. On a single test, `vkDestroyInstance` takes 3 ms (without validation layers, method already compiled), I haven't tested for other handle types, though for smaller ones (like `VkBuffer`) I suppose it would be faster. Reference counting is really simple as I've done it, you just increment/decrement a counter when the handle itself or children of it are created/destroyed, and conditionally run the destructor (if counter reaches 0) every time the counter is decremented. The destructor is an anonymous function stored inside the parent handle. That storage may introduce some overhead, I'm not really sure how much for now, I'll have to do some more benchmarking.

Feature 3. may introduce the most overhead because it allocates a `Vector{Any}` for every instance. A more performant alternative I had was to define fields for each struct that needed to store pointed objects, but I went for simplicity. I'm relying on future benchmarks to properly gauge the introduced overhead and keep it minimal, while keeping compile times to a minimum. The generator should be clean enough to make it not too hard to experiment with multiple designs.

**Comment by serenity4** [comment]
> I think VulkanHpp is a good reference to determine what kind of features should be provided by Vulkan.jl.

Indeed, thanks for the link! That's what I'd expect for it as well, so it's a high-level library _for developers who want to mess with Vulkan_.

**Comment by serenity4** [comment]
VulkanHpp implements the exact same things I had in mind (and more), a lot of which is already functional, so that's a good sign. Hopefully I can soon clean up and finish the waiting PR on Vulkan.jl.

**Comment by Gnimuc** [comment]
> Reference counting is really simple as I've done it, you just increment/decrement a counter when the handle itself or children of it are created/destroyed, and conditionally run the destructor (if counter reaches 0) every time the counter is decremented.

To make it thread safe, a little bit more work may need to be done, the counter should be atomic at least.

**Comment by serenity4** [comment]
> To make it thread safe, a little bit more work may need to be done, the counter should be atomic at least.

Yep, that's on my list, along with `atomic_add!`/`atomic_sub!` operations for incrementing/decrementing.
