### ISSUE TITLE
Add API methods for calling into function pointers

### ISSUE THREAD

**Issue by serenity4** [JuliaGPU/VulkanCore.jl#44]
When we transitioned to the new Clang generator, I didn't notice that we lost the definitions for API functions that take a function pointer and `ccall` into it, like we had [here](https://github.com/JuliaGPU/VulkanCore.jl/blob/3134e6ba7e56de92d81b70a7167cf6328557b6d6/gen/vk_api.jl#L3446).

Would it be possible to add these definitions to the generator? Originally we just [parsed the API file](https://github.com/JuliaGPU/VulkanCore.jl/blob/3134e6ba7e56de92d81b70a7167cf6328557b6d6/gen/generator.jl#L49) after the generator was run to add them, but I am wondering if there is a more natural way to do it.

**Comment by Gnimuc** [comment]
It looks like that's actually the simplest way. 

Another way is writing a custom Printer pass and manipulating the expressions(`ctx.dag.nodes[xxx].exprs`) of every function node, which is a little bit verbose. 

I think this is a good feature that should be provided by Clang.jl.

**Comment by Gnimuc** [comment]
Should be fixed by #45
