### ISSUE TITLE
Using Ref{T} instead of Ptr{T}

### ISSUE THREAD

**Issue by Distjubo** [JuliaGPU/VulkanCore.jl#8]
Just a question. Wouldn't it be possible to use `Ref{T}` instead of `Ptr{T}` in `VulkanCore.jl/gen/api/vk_common_1.0.0.jl`? Is there any specific reason you are using `Ptr` instead? Because as far as I understand, `Ref`s and `Ptr`s behave the same when used as parameters to c functions, but `Ref`s protect their values from Julias GC.

**Comment by yuyichao** [comment]
That's not the case.

**Comment by Distjubo** [comment]
Could you tell me what's the difference then? If I understand correctly, a pointer to a c type should be a `Ref` in Julia. But for example [this line of code](https://github.com/JuliaGPU/VulkanCore.jl/blob/master/gen/api/vk_1.0.0.jl#L9) uses `Ptr`.

**Comment by yuyichao** [comment]
>  If I understand correctly, a pointer to a c type should be a `Ref` in Julia.

No, that's wrong and

> Because as far as I understand, Refs and Ptrs behave the same when used as parameters to c functions, but Refs protect their values from Julias GC.

There's no such magic at all.

`Ref{T}` is treated similar to `Ptr{T}` for `ccall` ABI and has some convenient conversion methods defining on it for passing object by reference. With the correct conversion defined for the type you want, there's no difference between them at all.

For ccall, you can replace `Ptr` with `Ref` most of the time but blindly replacing `Ptr` with `Ref` is almost always wrong. This is especially the case for type definitions where you basically never want `Ref`.

**Comment by yuyichao** [comment]
Also, don't ask questions here, use http://discourse.julialang.org/

**Comment by Distjubo** [comment]
> No, that's wrong and

That's what I read in [the docs](http://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/#ccall-cfunction-argument-translation-guide).  Anyways, thank you

**Comment by yuyichao** [comment]
The doc you linked clearly listed both as options.

**Comment by Distjubo** [comment]
Thats what it says for me in the arguments section

>T*
> - `Ref{T}`, where `T` is the Julia type corresponding to `T`
> - argument value will be copied if it is an `isbits` type otherwise, the value must be a valid Julia object

And also, in [the bits type section](http://docs.julialang.org/en/stable/manual/calling-c-and-fortran-code/#bits-types) it says the following:
>`Ref{T}`
>    Behaves like a `Ptr{T}` that owns its memory.

**Comment by yuyichao** [comment]
It also says

> `void*`
>
>    depends on how this parameter is used, first translate this to the intended pointer type, then determine the Julia equivalent using the remaining rules in this list
>    this argument may be declared as Ptr{Void}, if it really is just an unknown pointer

This is also only about the builtin conversion and there's no magic difference for custom conversion.

More importantly this is about

> `ccall`/`cfunction` argument translation guide

and has nothing to do with anything in `VulkanCore.jl/gen/api/vk_common_1.0.0.jl`, which is what I was replying to begin with.

**Comment by yuyichao** [comment]
And anyway, no more reply here, ask on discourse instead if you have more questions.

**Comment by Distjubo** [comment]
Ok thanks
